In [2]:
import sqlite3
import pandas as pd

# Connect to your database
conn = sqlite3.connect('data/weather.db')

# Read from the correct tables
locations_df = pd.read_sql_query("SELECT * FROM locations LIMIT 10", conn)
print("Locations:")
print(locations_df)

readings_df = pd.read_sql_query("SELECT * FROM readings LIMIT 10", conn)
print("\nReadings:")
print(readings_df)

# Check table structure
cursor = conn.cursor()
cursor.execute("PRAGMA table_info(readings)")
print("\nReadings table structure:")
print(cursor.fetchall())

conn.close()

Locations:
   id            city country      lat       lon                tz  is_active  \
0   1  Salt Lake City      US  40.7608 -111.8910    America/Denver          1
1   2       Knoxville      US  35.9606  -83.9207  America/New_York          1
2   3           Tokyo      JP  35.6828  139.7595        Asia/Tokyo          1
3   4       knoxville      us      NaN       NaN              None          1
4   5       Nashville      US      NaN       NaN              None          1
5   6        St Louis      US      NaN       NaN              None          1
6   7      Miniapolis      US      NaN       NaN              None          1
7   8       Testville      US      NaN       NaN              None          1
8   9          Austin      US      NaN       NaN              None          1

            created_at
0  2025-07-28 06:51:20
1  2025-07-28 06:51:20
2  2025-07-28 06:51:20
3  2025-07-14 11:27:49
4  2025-07-10 22:34:50
5  2025-07-10 23:07:36
6  2025-07-12 23:01:58
7  2025-07-12 23:06:01
8  2025-07-14 13:39:07

Readings:
   id            timestamp            city country   temp  feels_like  \
0   1  2025-07-10T16:59:05  Salt Lake City      US  28.30       27.32
1   2  2025-07-10T16:58:34       Knoxville      US  28.56       31.95
2   3  2025-07-10T16:58:03           Tokyo      JP  22.86       23.47
3   4  2025-07-10T16:59:05  Salt Lake City      US  28.30       27.32
4   5  2025-07-10T16:58:34       Knoxville      US  28.56       31.95
5   6  2025-07-10T16:58:03           Tokyo      JP  22.86       23.47
6   7  2025-07-10T16:58:34       Knoxville      US  28.56       31.95
7   8  2025-07-10T16:58:52           Miami      US  32.21       39.21
8   9  2025-07-10T17:03:11        St Louis      US  31.83       35.29
9  10  2025-07-10T16:58:52           Miami      US  32.21       39.21

   humidity  pressure weather_summary weather_detail  wind_speed  wind_deg  \
0        30    1016.0          Clouds     few clouds        4.63       300
1        71    1016.0          Clouds  broken clouds        2.57       240
2        87    1013.0          Clouds  broken clouds        5.14        30
3        30    1016.0          Clouds     few clouds        4.63       300
4        71    1016.0          Clouds  broken clouds        2.57       240
5        87    1013.0          Clouds  broken clouds        5.14        30
6        71    1016.0          Clouds  broken clouds        2.57       240
7        70    1019.0    Thunderstorm   thunderstorm        5.66       150
8        55    1015.0           Clear      clear sky        2.57         0
9        70    1019.0    Thunderstorm   thunderstorm        5.66       150

   clouds  visibility                  fetched_at           created_at
0      20       10000  2025-07-10T17:01:18.637092  2025-07-10 17:01:18
1      75       10000  2025-07-10T17:01:19.730083  2025-07-10 17:01:19
2      75       10000  2025-07-10T17:01:20.803822  2025-07-10 17:01:20
3      20       10000  2025-07-10T17:01:21.879868  2025-07-10 17:01:21
4      75       10000  2025-07-10T17:01:22.949831  2025-07-10 17:01:22
5      75       10000  2025-07-10T17:01:24.021898  2025-07-10 17:01:24
6      75       10000  2025-07-10T17:01:34.850661  2025-07-10 17:01:34
7      75       10000  2025-07-10T17:01:53.598328  2025-07-10 17:01:53
8       0       10000  2025-07-10T17:03:58.763303  2025-07-10 17:03:58
9      75       10000  2025-07-10T17:04:05.469186  2025-07-10 17:04:05

Readings table structure:
[(0, 'id', 'INTEGER', 0, None, 1), (1, 'timestamp', 'TEXT', 1, None, 0), (2, 'city', 'TEXT', 1, None, 0), (3, 'country', 'TEXT', 1, None, 0), (4, 'temp', 'REAL', 1, None, 0), (5, 'feels_like', 'REAL', 0, None, 0), (6, 'humidity', 'INTEGER', 0, None, 0), (7, 'pressure', 'REAL', 0, None, 0), (8, 'weather_summary', 'TEXT', 0, None, 0), (9, 'weather_detail', 'TEXT', 0, None, 0), (10, 'wind_speed', 'REAL', 0, None, 0), (11, 'wind_deg', 'INTEGER', 0, None, 0), (12, 'clouds', 'INTEGER', 0, None, 0), (13, 'visibility', 'INTEGER', 0, None, 0), (14, 'fetched_at', 'TEXT', 0, None, 0), (15, 'created_at', 'TEXT', 0, 'CURRENT_TIMESTAMP', 0)]

In [11]:
import sqlite3
import pandas as pd

# Reconnect to your database
conn = sqlite3.connect('data/weather.db')

# Delete temperatures over 100°F (since you said anything over 100 is bad)
cursor = conn.cursor()
cursor.execute("DELETE FROM readings WHERE temp > 100")
conn.commit()
print(f"Deleted {cursor.rowcount} bad temperature records over 100°F")

# Verify the cleanup worked
remaining_bad = pd.read_sql_query("SELECT COUNT(*) FROM readings WHERE temp > 100", conn)
print(f"Remaining bad records over 100°F: {remaining_bad.iloc[0,0]}")

# Check your data now
clean_data = pd.read_sql_query("SELECT * FROM readings ORDER BY temp DESC LIMIT 10", conn)
print("Highest temperatures remaining:")
print(clean_data)

conn.close()

Deleted 0 bad temperature records over 100°F
Remaining bad records over 100°F: 0
Highest temperatures remaining:
     id            timestamp            city country  temp  feels_like  \
0  2709  2025-07-28T02:20:08  Salt Lake City      US  87.7        84.0
1  2710  2025-07-28T02:20:08  Salt Lake City      US  87.7        84.0
2  2719  2025-07-28T02:19:46        St Louis      US  83.8        94.1
3  2720  2025-07-28T02:19:46        St Louis      US  83.8        94.1
4  2717  2025-07-28T02:19:00       Nashville      US  83.5        92.2
5  2718  2025-07-28T02:19:00       Nashville      US  83.5        92.2
6  2792  2025-07-28T04:20:43        St Louis      US  83.2        93.7
7  2793  2025-07-28T04:20:43        St Louis      US  83.2        93.7
8  2821  2025-07-28T05:13:33        St Louis      US  83.1        91.9
9  2771  2025-07-28T03:42:03       Nashville      US  82.7        89.3

   humidity  pressure weather_summary weather_detail  wind_speed  wind_deg  \
0        11    1014.0          Clouds     few clouds        0.45       217
1        11    1014.0          Clouds     few clouds        0.45       217
2        82    1018.0           Clear      clear sky        1.54       140
3        82    1018.0           Clear      clear sky        1.54       140
4        79    1020.0           Clear      clear sky        1.53       288
5        79    1020.0           Clear      clear sky        1.53       288
6        85    1017.0           Clear      clear sky        4.61       170
7        85    1017.0           Clear      clear sky        4.61       170
8        81    1018.0           Clear      clear sky        4.61       200
9        76    1020.0          Clouds     few clouds        3.44       240

   clouds  visibility                  fetched_at           created_at
0      15       10000  2025-07-28T02:21:47.121709  2025-07-28 02:21:47
1      15       10000  2025-07-28T02:21:48.016513  2025-07-28 02:21:48
2       0       10000  2025-07-28T02:21:57.026162  2025-07-28 02:21:57
3       0       10000  2025-07-28T02:21:58.021572  2025-07-28 02:21:58
4       1       10000  2025-07-28T02:21:55.089873  2025-07-28 02:21:55
5       1       10000  2025-07-28T02:21:56.020645  2025-07-28 02:21:56
6       0       10000  2025-07-28T04:20:43.734850  2025-07-28 04:20:43
7       0       10000  2025-07-28T04:20:44.718071  2025-07-28 04:20:44
8       0       10000  2025-07-28T05:13:33.520189  2025-07-28 05:13:33
9      20       10000  2025-07-28T03:43:00.928897  2025-07-28 03:43:00

In [12]:
# Run this in Jupyter to permanently fix the database
import sqlite3

conn = sqlite3.connect('data/weather.db')
cursor = conn.cursor()

# Delete ALL readings over 100°F
cursor.execute("DELETE FROM readings WHERE temp > 37.78")  # 37.78°C = 100°F
conn.commit()

print(f"Deleted {cursor.rowcount} bad records")
conn.close()

Deleted 122 bad records

In [14]:
import pandas as pd
import numpy as np
from scipy import stats

# Load your data
conn = sqlite3.connect('data/weather.db')
df = pd.read_sql_query("SELECT * FROM readings", conn)

# Remove outliers using Z-score (anything >3 standard deviations)
z_scores = np.abs(stats.zscore(df['temp']))
df_clean = df[z_scores < 3]

# Replace the entire table with cleaned data
df_clean.to_sql('readings', conn, if_exists='replace', index=False)
conn.close()

In [15]:
cursor.execute("DELETE FROM readings WHERE temp > 40")
conn.commit()

ProgrammingError: Cannot operate on a closed database.

In [16]:
import sqlite3
import pandas as pd
from scipy import stats
import numpy as np

# Complete database cleaning script
def clean_weather_database():
    with sqlite3.connect('data/weather.db') as conn:
        # Read all data
        df = pd.read_sql_query("SELECT * FROM readings", conn)
        print(f"Original records: {len(df)}")
        
        # Remove extreme outliers using Z-score
        z_scores = np.abs(stats.zscore(df['temp']))
        df_clean = df[z_scores < 3]  # Keep only within 3 standard deviations
        
        # Also remove anything above 40°C (104°F) as backup
        df_clean = df_clean[df_clean['temp'] <= 40]
        
        print(f"Records after cleaning: {len(df_clean)}")
        print(f"Deleted {len(df) - len(df_clean)} bad records")
        
        # Replace entire table with cleaned data
        df_clean.to_sql('readings', conn, if_exists='replace', index=False)
        
        print("Database cleaned successfully!")

# Run the cleaning
clean_weather_database()

Original records: 2754
Records after cleaning: 2754
Deleted 0 bad records
Database cleaned successfully!

In [ ]:
import pandas as pd

df = pd.read_csv("weather_data.csv")
df.head()

In [1]:
import pandas as pd

df = pd.read_csv("weather_data.csv")
df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'weather_data.csv'

In [2]:
import pandas as pd

# Direct path to the file
df = pd.read_csv(r"C:\Users\snoep_a5dedf8\Desktop\JTC\final\WeatherDashboard-Shanna\data\weather_data.csv")

df.head()  # Preview the first few rows

,id,city,country,lat,lon,tz,is_active,created_at
0,1,Salt Lake City,US,40.7608,-111.8910,America/Denver,1,2025-07-29 00:33:33
1,2,Knoxville,US,35.9606,-83.9207,America/New_York,1,2025-07-29 00:33:33
2,3,Tokyo,JP,35.6828,139.7595,Asia/Tokyo,1,2025-07-29 00:33:33
3,4,knoxville,us,NaN,NaN,NaN,1,2025-07-14 11:27:49
4,5,Nashville,US,NaN,NaN,NaN,1,2025-07-10 22:34:50

In [3]:
import sqlite3

conn = sqlite3.connect(r"C:\Users\snoep_a5dedf8\Desktop\JTC\final\WeatherDashboard-Shanna\data\weather.db")
query = "SELECT * FROM readings;"  # Or whatever table name you use
df = pd.read_sql_query(query, conn)

df.head()

,id,timestamp,city,country,temp,feels_like,humidity,pressure,weather_summary,weather_detail,wind_speed,wind_deg,clouds,visibility,fetched_at,created_at
0,1.0,2025-07-10T16:59:05,Salt Lake City,US,28.30,27.32,30,1016.0,Clouds,few clouds,4.63,300,20,10000,2025-07-10T17:01:18.637092,2025-07-10 17:01:18
1,2.0,2025-07-10T16:58:34,Knoxville,US,28.56,31.95,71,1016.0,Clouds,broken clouds,2.57,240,75,10000,2025-07-10T17:01:19.730083,2025-07-10 17:01:19
2,3.0,2025-07-10T16:58:03,Tokyo,JP,22.86,23.47,87,1013.0,Clouds,broken clouds,5.14,30,75,10000,2025-07-10T17:01:20.803822,2025-07-10 17:01:20
3,4.0,2025-07-10T16:59:05,Salt Lake City,US,28.30,27.32,30,1016.0,Clouds,few clouds,4.63,300,20,10000,2025-07-10T17:01:21.879868,2025-07-10 17:01:21
4,5.0,2025-07-10T16:58:34,Knoxville,US,28.56,31.95,71,1016.0,Clouds,broken clouds,2.57,240,75,10000,2025-07-10T17:01:22.949831,2025-07-10 17:01:22

In [4]:
import pandas as pd

# Load it
df = pd.read_csv(r"C:\Users\snoep_a5dedf8\Desktop\JTC\final\WeatherDashboard-Shanna\data\weather_data.csv")

# Convert timestamp
df["created_at"] = pd.to_datetime(df["created_at"])

# Fill missing lat/lon manually or drop rows
df.dropna(subset=["lat", "lon", "tz"], inplace=True)

# Optional: Normalize column formats
df["city"] = df["city"].str.title().str.strip()
df["tz"] = df["tz"].fillna("Unknown")  # if you want to keep incomplete rows

# Review result
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, 0 to 2
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          3 non-null      int64
 1   city        3 non-null      object
 2   country     3 non-null      object
 3   lat         3 non-null      float64
 4   lon         3 non-null      float64
 5   tz          3 non-null      object
 6   is_active   3 non-null      int64
 7   created_at  3 non-null      datetime64[ns]
dtypes: datetime64[ns](1), float64(2), int64(2), object(3)
memory usage: 216.0+ bytes

,id,city,country,lat,lon,tz,is_active,created_at
0,1,Salt Lake City,US,40.7608,-111.8910,America/Denver,1,2025-07-29 00:33:33
1,2,Knoxville,US,35.9606,-83.9207,America/New_York,1,2025-07-29 00:33:33
2,3,Tokyo,JP,35.6828,139.7595,Asia/Tokyo,1,2025-07-29 00:33:33

In [6]:
city_tz_map = {
    "Knoxville": "America/New_York",
    "Salt Lake City": "America/Denver",
    "Tokyo": "Asia/Tokyo",
    "Nashville": "America/Chicago"
}

df["tz"] = df.apply(lambda x: city_tz_map.get(x["city"], x["tz"]), axis=1)

In [7]:
import pandas as pd

# Load raw data
df = pd.read_csv(r"C:\Users\snoep_a5dedf8\Desktop\JTC\final\WeatherDashboard-Shanna\data\weather_data.csv")

# Convert timestamps
df["created_at"] = pd.to_datetime(df["created_at"], errors="coerce")

# Drop rows missing critical values
df.dropna(subset=["lat", "lon", "tz", "created_at"], inplace=True)

# Normalize text fields
df["city"] = df["city"].str.title().str.strip()
df["tz"] = df["tz"].str.strip()

# Optional: add validation for geo bounds
df = df[(df["lat"].between(-90, 90)) & (df["lon"].between(-180, 180))]

# If there's a temperature column, clean that too
if "temp" in df.columns:
    df = df[(df["temp"] >= 50) & (df["temp"] <= 130)]

# Reset index for fresh view
df.reset_index(drop=True, inplace=True)

# Preview cleaned data
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          3 non-null      int64
 1   city        3 non-null      object
 2   country     3 non-null      object
 3   lat         3 non-null      float64
 4   lon         3 non-null      float64
 5   tz          3 non-null      object
 6   is_active   3 non-null      int64
 7   created_at  3 non-null      datetime64[ns]
dtypes: datetime64[ns](1), float64(2), int64(2), object(3)
memory usage: 324.0+ bytes

,id,city,country,lat,lon,tz,is_active,created_at
0,1,Salt Lake City,US,40.7608,-111.8910,America/Denver,1,2025-07-29 00:33:33
1,2,Knoxville,US,35.9606,-83.9207,America/New_York,1,2025-07-29 00:33:33
2,3,Tokyo,JP,35.6828,139.7595,Asia/Tokyo,1,2025-07-29 00:33:33

In [8]:
df.to_csv("weather_data_cleaned.csv", index=False)

In [9]:
import sqlite3
conn = sqlite3.connect("weather.db")
df.to_sql("locations_cleaned", conn, if_exists="replace", index=False)

3

In [10]:
import pandas as pd

# Load file
readings_df = pd.read_csv(r"C:\Users\snoep_a5dedf8\Desktop\JTC\final\WeatherDashboard-Shanna\data\weather_readings.csv")

# Convert timestamp safely
readings_df["timestamp"] = pd.to_datetime(readings_df["timestamp"], errors="coerce")

# Drop rows with essential missing data
readings_df.dropna(subset=["temp", "humidity", "pressure", "timestamp"], inplace=True)

# Sanitize value ranges
readings_df = readings_df[
    (readings_df["temp"].between(50, 130)) &
    (readings_df["humidity"].between(0, 100)) &
    (readings_df["pressure"].between(900, 1100)) &
    (readings_df["wind_speed"].between(0, 150))
]

# Normalize text fields if present
if "city" in readings_df.columns:
    readings_df["city"] = readings_df["city"].str.title().str.strip()

# Reset index and preview
readings_df.reset_index(drop=True, inplace=True)
readings_df.info()
readings_df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               0 non-null      int64
 1   timestamp        0 non-null      datetime64[ns]
 2   city             0 non-null      object
 3   country          0 non-null      object
 4   temp             0 non-null      float64
 5   feels_like       0 non-null      float64
 6   humidity         0 non-null      int64
 7   pressure         0 non-null      float64
 8   weather_summary  0 non-null      object
 9   weather_detail   0 non-null      object
 10  wind_speed       0 non-null      float64
 11  wind_deg         0 non-null      int64
 12  clouds           0 non-null      int64
 13  visibility       0 non-null      int64
 14  fetched_at       0 non-null      object
 15  created_at       0 non-null      object
dtypes: datetime64[ns](1), float64(4), int64(5), object(6)
memory usage: 132.0+ bytes

Empty DataFrame
Columns: [id, timestamp, city, country, temp, feels_like, humidity, pressure, weather_summary, weather_detail, wind_speed, wind_deg, clouds, visibility, fetched_at, created_at]
Index: []

In [12]:
def standardize_weather_row(row):
    return {
        "current time": pd.to_datetime(row.get("timestamp") or row.get("created_at")).strftime("%m-%d-%y %H:%M:%S"),
        "City": row.get("city", "").title().strip(),
        "State": row.get("state", "").title().strip(),
        "Country": row.get("country", "US"),
        "Temperature": round(row.get("temp", 0), 1),
        "Feels Like": round(row.get("feels_like", row.get("temp", 0)), 1),
        "Humidity": round(row.get("humidity", 0), 1),
        "Precipitation": round(row.get("precipitation", 0.0), 2),
        "Pressure": round(row.get("pressure", 0), 1),
        "Wind Speed": round(row.get("wind_speed", 0), 1),
        "Wind Direction": row.get("wind_dir", "Unknown"),
        "Visibility": row.get("visibility", 0),
        "Sunrise": row.get("sunrise", ""),
        "Sunset": row.get("sunset", "")
    }

In [13]:
cleaned_df = raw_df.apply(standardize_weather_row, axis=1, result_type='expand')

NameError: name 'raw_df' is not defined

In [14]:
from IPython.display import display

display(cleaned_data_df.head())
display(cleaned_readings_df.info())

NameError: name 'cleaned_data_df' is not defined

In [15]:
raw_df = pd.read_csv(r'WeatherDashboard-Shanna\data\weather_data.csv')  # or whichever file you're starting with

FileNotFoundError: [Errno 2] No such file or directory: 'WeatherDashboard-Shanna\\data\\weather_data.csv'

In [16]:
import pandas as pd

# Load both CSVs
df_weather_data = pd.read_csv(r'WeatherDashboard-Shanna\data\weather_data.csv')
df_weather_readings = pd.read_csv(r'WeatherDashboard-Shanna\data\weather_readings.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'WeatherDashboard-Shanna\\data\\weather_data.csv'

In [17]:
# 📥 Step 1: Load your raw data
import pandas as pd
from IPython.display import display

# Load both CSVs
df_weather_data = pd.read_csv('weather_data.csv')
df_weather_readings = pd.read_csv('weather_readings.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'weather_data.csv'

In [18]:
import pandas as pd
from IPython.display import display

# ✅ Correct paths — now separated properly
path_readings = r'WeatherDashboard-Shanna\data\weather_readings.csv'
path_data = r'WeatherDashboard-Shanna\data\weather_data.csv'

# 📥 Load both CSVs
df_weather_readings = pd.read_csv(path_readings)
df_weather_data = pd.read_csv(path_data)

FileNotFoundError: [Errno 2] No such file or directory: 'WeatherDashboard-Shanna\\data\\weather_readings.csv'

In [19]:
import os

os.listdir()  # See what folder Jupyter thinks you're in

['.env',
 '.gitignore',
 '.ipynb_checkpoints',
 '.pytest_cache',
 '.venv',
 'automated_weather_tracker.py',
 'config.py',
 'data',
 'docs',
 'features',
 'icons',
 'main.py',
 'README.md',
 'screenshots',
 'services',
 'tests',
 'Untitled.ipynb',
 'utils',
 'weather.db',
 'weather_data_cleaned.csv',
 'weather_data_fetcher.py',
 'weather_db.py',
 'weather_display_ui.py',
 'wireframe',
 '__pycache__']

In [20]:
import pandas as pd
from IPython.display import display

# File paths — assuming your notebook is in the root folder
path_readings = r'data/weather_readings.csv'
path_data = r'data/weather_data.csv'

In [21]:
# Load the data
df_weather_readings = pd.read_csv(path_readings)
df_weather_data = pd.read_csv(path_data)

In [22]:
# Inspect structure and sample data
display(df_weather_readings.head())
display(df_weather_readings.info())

display(df_weather_data.head())
display(df_weather_data.info())

,id,timestamp,city,country,temp,feels_like,humidity,pressure,weather_summary,weather_detail,wind_speed,wind_deg,clouds,visibility,fetched_at,created_at
0,904,2025-07-16T06:41:59,Knoxville,US,23.59,24.43,93,1017.0,Mist,mist,0.00,0,0,3219,2025-07-16T06:41:59.738812,2025-07-16 06:41:59
1,889,2025-07-16T06:29:19,Salt Lake City,US,24.32,24.01,46,1013.0,Clouds,overcast clouds,2.95,119,89,10000,2025-07-16T06:32:49.902828,2025-07-16 06:32:49
2,888,2025-07-16T06:29:19,Salt Lake City,US,24.32,24.01,46,1013.0,Clouds,overcast clouds,2.95,119,89,10000,2025-07-16T06:32:48.938402,2025-07-16 06:32:48
3,881,2025-07-16T06:29:19,Salt Lake City,US,24.32,24.01,46,1013.0,Clouds,overcast clouds,2.95,119,89,10000,2025-07-16T06:31:24.035171,2025-07-16 06:31:24
4,899,2025-07-16T06:27:54,St Louis,US,24.03,24.89,92,1013.0,Clear,clear sky,0.45,317,0,10000,2025-07-16T06:32:59.918339,2025-07-16 06:32:59

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 904 entries, 0 to 903
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               904 non-null    int64
 1   timestamp        904 non-null    object
 2   city             904 non-null    object
 3   country          904 non-null    object
 4   temp             904 non-null    float64
 5   feels_like       904 non-null    float64
 6   humidity         904 non-null    int64
 7   pressure         904 non-null    float64
 8   weather_summary  904 non-null    object
 9   weather_detail   904 non-null    object
 10  wind_speed       904 non-null    float64
 11  wind_deg         904 non-null    int64
 12  clouds           904 non-null    int64
 13  visibility       904 non-null    int64
 14  fetched_at       904 non-null    object
 15  created_at       904 non-null    object
dtypes: float64(4), int64(5), object(7)
memory usage: 113.1+ KB

None

,id,city,country,lat,lon,tz,is_active,created_at
0,1,Salt Lake City,US,40.7608,-111.8910,America/Denver,1,2025-07-29 00:33:33
1,2,Knoxville,US,35.9606,-83.9207,America/New_York,1,2025-07-29 00:33:33
2,3,Tokyo,JP,35.6828,139.7595,Asia/Tokyo,1,2025-07-29 00:33:33
3,4,knoxville,us,NaN,NaN,NaN,1,2025-07-14 11:27:49
4,5,Nashville,US,NaN,NaN,NaN,1,2025-07-10 22:34:50

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          9 non-null      int64
 1   city        9 non-null      object
 2   country     9 non-null      object
 3   lat         3 non-null      float64
 4   lon         3 non-null      float64
 5   tz          3 non-null      object
 6   is_active   9 non-null      int64
 7   created_at  9 non-null      object
dtypes: float64(2), int64(2), object(4)
memory usage: 708.0+ bytes

None

In [23]:
def clean_weather_row(row):
    row = row.copy()

    # Time & location fields
    row['current time'] = pd.to_datetime(row.get('current time') or row.get('timestamp') or row.get('date'), errors='coerce')
    row['City'] = str(row.get('City') or row.get('city')).strip()
    row['State'] = str(row.get('State', '')).strip()
    row['Country'] = str(row.get('Country', 'USA')).strip()

    def to_float(val):
        try:
            return float(str(val).replace('%', '').strip())
        except:
            return None

    # Measurements
    row['Temperature'] = to_float(row.get('Temperature') or row.get('temp_f') or row.get('temp_c'))
    row['Feels Like'] = to_float(row.get('Feels Like'))
    row['Humidity'] = to_float(row.get('Humidity'))
    row['Precipitation'] = to_float(row.get('Precipitation'))
    row['Pressure'] = to_float(row.get('Pressure'))
    row['Wind Speed'] = to_float(row.get('Wind Speed'))
    row['Wind Direction'] = str(row.get('Wind Direction', 'Unknown')).strip()
    row['Visibility'] = to_float(row.get('Visibility'))

    # Sunrise/Sunset
    row['Sunrise'] = pd.to_datetime(row.get('Sunrise'), errors='coerce')
    row['Sunset'] = pd.to_datetime(row.get('Sunset'), errors='coerce')

    return row

In [24]:
cleaned_readings_df = df_weather_readings.apply(clean_weather_row, axis=1, result_type='expand')
cleaned_data_df = df_weather_data.apply(clean_weather_row, axis=1, result_type='expand')

In [25]:
standard_columns = [
    'current time', 'City', 'State', 'Country', 'Temperature',
    'Feels Like', 'Humidity', 'Precipitation', 'Pressure',
    'Wind Speed', 'Wind Direction', 'Visibility', 'Sunrise', 'Sunset'
]

cleaned_readings_df = cleaned_readings_df[standard_columns]
cleaned_data_df = cleaned_data_df[standard_columns]

In [26]:
display(cleaned_readings_df.head())
display(cleaned_data_df.head())

,current time,City,State,Country,Temperature,Feels Like,Humidity,Precipitation,Pressure,Wind Speed,Wind Direction,Visibility,Sunrise,Sunset
0,2025-07-16 06:41:59,Knoxville,,USA,None,None,None,None,None,None,Unknown,None,None,None
1,2025-07-16 06:29:19,Salt Lake City,,USA,None,None,None,None,None,None,Unknown,None,None,None
2,2025-07-16 06:29:19,Salt Lake City,,USA,None,None,None,None,None,None,Unknown,None,None,None
3,2025-07-16 06:29:19,Salt Lake City,,USA,None,None,None,None,None,None,Unknown,None,None,None
4,2025-07-16 06:27:54,St Louis,,USA,None,None,None,None,None,None,Unknown,None,None,None

,current time,City,State,Country,Temperature,Feels Like,Humidity,Precipitation,Pressure,Wind Speed,Wind Direction,Visibility,Sunrise,Sunset
0,None,Salt Lake City,,USA,None,None,None,None,None,None,Unknown,None,None,None
1,None,Knoxville,,USA,None,None,None,None,None,None,Unknown,None,None,None
2,None,Tokyo,,USA,None,None,None,None,None,None,Unknown,None,None,None
3,None,knoxville,,USA,None,None,None,None,None,None,Unknown,None,None,None
4,None,Nashville,,USA,None,None,None,None,None,None,Unknown,None,None,None

In [27]:
display(df_weather_readings.head(10))
display(df_weather_data.head(10))

,id,timestamp,city,country,temp,feels_like,humidity,pressure,weather_summary,weather_detail,wind_speed,wind_deg,clouds,visibility,fetched_at,created_at
0,904,2025-07-16T06:41:59,Knoxville,US,23.59,24.43,93,1017.0,Mist,mist,0.00,0,0,3219,2025-07-16T06:41:59.738812,2025-07-16 06:41:59
1,889,2025-07-16T06:29:19,Salt Lake City,US,24.32,24.01,46,1013.0,Clouds,overcast clouds,2.95,119,89,10000,2025-07-16T06:32:49.902828,2025-07-16 06:32:49
2,888,2025-07-16T06:29:19,Salt Lake City,US,24.32,24.01,46,1013.0,Clouds,overcast clouds,2.95,119,89,10000,2025-07-16T06:32:48.938402,2025-07-16 06:32:48
3,881,2025-07-16T06:29:19,Salt Lake City,US,24.32,24.01,46,1013.0,Clouds,overcast clouds,2.95,119,89,10000,2025-07-16T06:31:24.035171,2025-07-16 06:31:24
4,899,2025-07-16T06:27:54,St Louis,US,24.03,24.89,92,1013.0,Clear,clear sky,0.45,317,0,10000,2025-07-16T06:32:59.918339,2025-07-16 06:32:59
5,898,2025-07-16T06:27:54,St Louis,US,24.03,24.89,92,1013.0,Clear,clear sky,0.45,317,0,10000,2025-07-16T06:32:58.862577,2025-07-16 06:32:58
6,886,2025-07-16T06:27:54,St Louis,US,24.03,24.89,92,1013.0,Clear,clear sky,0.45,317,0,10000,2025-07-16T06:31:29.390639,2025-07-16 06:31:29
7,903,2025-07-16T06:27:20,Knoxville,US,23.83,24.67,92,1017.0,Mist,mist,0.45,297,40,6437,2025-07-16T06:33:20.586055,2025-07-16 06:33:20
8,902,2025-07-16T06:27:20,Knoxville,US,23.83,24.67,92,1017.0,Mist,mist,0.45,297,40,6437,2025-07-16T06:33:07.073833,2025-07-16 06:33:07
9,895,2025-07-16T06:27:20,Knoxville,US,23.83,24.67,92,1017.0,Mist,mist,0.45,297,40,6437,2025-07-16T06:32:55.864027,2025-07-16 06:32:55

,id,city,country,lat,lon,tz,is_active,created_at
0,1,Salt Lake City,US,40.7608,-111.8910,America/Denver,1,2025-07-29 00:33:33
1,2,Knoxville,US,35.9606,-83.9207,America/New_York,1,2025-07-29 00:33:33
2,3,Tokyo,JP,35.6828,139.7595,Asia/Tokyo,1,2025-07-29 00:33:33
3,4,knoxville,us,NaN,NaN,NaN,1,2025-07-14 11:27:49
4,5,Nashville,US,NaN,NaN,NaN,1,2025-07-10 22:34:50
5,6,St Louis,US,NaN,NaN,NaN,1,2025-07-10 23:07:36
6,7,Miniapolis,US,NaN,NaN,NaN,1,2025-07-12 23:01:58
7,8,Testville,US,NaN,NaN,NaN,1,2025-07-12 23:06:01
8,9,Austin,US,NaN,NaN,NaN,1,2025-07-14 13:39:07

In [28]:

df = pd.read_csv(r'data/weather_readings.csv')

In [29]:
df = df.drop_duplicates()

In [30]:
# Essential fields you need populated
required = ['timestamp', 'city', 'country', 'temp', 'feels_like', 'humidity', 'pressure', 'weather_summary']

df = df.dropna(subset=required)

In [31]:
df = df[~df['weather_description'].str.contains('0\.0,0\.0,0\.0', na=False)]

<>:1: SyntaxWarning: invalid escape sequence '\.'
<>:1: SyntaxWarning: invalid escape sequence '\.'
C:\Users\snoep_a5dedf8\AppData\Local\Temp\ipykernel_24232\1449999583.py:1: SyntaxWarning: invalid escape sequence '\.'
  df = df[~df['weather_description'].str.contains('0\.0,0\.0,0\.0', na=False)]
C:\Users\snoep_a5dedf8\AppData\Local\Temp\ipykernel_24232\1449999583.py:1: SyntaxWarning: invalid escape sequence '\.'
  df = df[~df['weather_description'].str.contains('0\.0,0\.0,0\.0', na=False)]

KeyError: 'weather_description'

In [32]:
print(df.columns.tolist())

['id', 'timestamp', 'city', 'country', 'temp', 'feels_like', 'humidity', 'pressure', 'weather_summary', 'weather_detail', 'wind_speed', 'wind_deg', 'clouds', 'visibility', 'fetched_at', 'created_at']

In [33]:
# Apply raw string formatting for safe regex
df = df[~df['weather_summary'].str.contains(r'0\.0,0\.0,0\.0', na=False)]
df = df[~df['weather_detail'].str.contains(r'0\.0,0\.0,0\.0', na=False)]

In [34]:
for col in ['weather_summary', 'weather_detail']:
    df[col] = df[col].replace('0.0,0.0,0.0', pd.NA)

In [35]:
df = df.dropna(subset=['weather_summary', 'weather_detail'])

In [36]:
print(df['weather_detail'].value_counts().head(20))

weather_detail
clear sky                      332
broken clouds                  275
few clouds                      92
overcast clouds                 74
scattered clouds                50
mist                            49
light intensity shower rain     24
thunderstorm                     4
heavy intensity shower rain      2
dust                             1
light rain                       1
Name: count, dtype: int64

In [37]:
# Flag but don’t immediately delete
df['temp_flag'] = df['temp'] > 105
df['feels_like_flag'] = df['feels_like'] > 105

In [38]:
print(df[['temp', 'feels_like']].max())

temp          295.0
feels_like    294.0
dtype: float64

In [39]:
df['temp_C'] = df['temp'] - 273.15
df['feels_like_C'] = df['feels_like'] - 273.15

In [40]:
# Drop extreme temperature outliers
df = df[df['temp'] <= 355.35]
df = df[df['feels_like'] <= 355.35]
max_kelvin = 355.35
df = df[df['temp'] <= max_kelvin]
df = df[df['feels_like'] <= max_kelvin]
print(f"Remaining rows: {len(df)}")

Remaining rows: 904

In [41]:
import pandas as pd

# Load your dataset
df = pd.read_csv('data/weather_readings.csv')

# Step 1: Drop duplicates and empty essentials
df = df.drop_duplicates()
required_cols = ['timestamp', 'city', 'country', 'temp', 'feels_like', 'humidity', 'pressure', 'weather_summary', 'weather_detail']
df = df.dropna(subset=required_cols)

# Step 2: Remove corrupt descriptions
for col in ['weather_summary', 'weather_detail']:
    df[col] = df[col].replace('0.0,0.0,0.0', pd.NA)
df = df.dropna(subset=['weather_summary', 'weather_detail'])

# Step 3: Convert timestamp + numeric columns
df['timestamp'] = pd.to_datetime(df['timestamp'], errors='coerce')
numeric_cols = ['temp', 'feels_like', 'humidity', 'pressure', 'wind_speed', 'wind_deg', 'clouds', 'visibility']
for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

# Step 4: Remove unrealistic temp readings (Kelvin > ~355K = 180°F)
max_kelvin = 355.35
df = df[df['temp'] <= max_kelvin]
df = df[df['feels_like'] <= max_kelvin]

# Step 5: Reset index for a clean slate
df = df.reset_index(drop=True)

In [42]:
# Make sure you're doing this:
df = pd.concat([df, new_predictions], ignore_index=True)

NameError: name 'new_predictions' is not defined